# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the project file
  PROJECT_FILE_PATH: 直达/直达.vcxproj

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: |
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $msbuildPath = & $vswherePath -latest -products * -find "MSBuild\**\Bin\MSBuild.exe" | Select-Object -First 1
        Write-Host "MSBuild Path: $msbuildPath"
        $projectPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "${{env.PROJECT_FILE_PATH}}"
        Write-Host "Project Path: $projectPath"
        & "$msbuildPath" /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 "$projectPath"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zhida-release
        path: 直达/bin/Release/x64/直达.exe
